authentication/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
]

django_canvas_hex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from map import urls as map_urls
from authentication import urls as auth_urls
from dashboard import urls as dashboard_urls
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^map/', include(map_urls, namespace='map')),
    url(r'^authentication/', include(auth_urls, namespace='authentication')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
]

map/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from views import create_map, game, pre_game, GameList, GameDetail, \
    UserList, UserDetail, game_test, TileList, action_detail, \
    generate_map, tile_detail, game_detail

urlpatterns = [
    url(r'^create_map/', create_map, name='create_map'),
    url(r'^game/(?P<gid>\d+)', game, name='game'),
    url(r'^pre_game/(?P<gid>\d+)', pre_game, name='pre_game'),
    url(r'^tile_list/(?P<game_id>[0-9]+)/$', TileList.as_view()),
    url(r'^tile_detail/(?P<pk>[0-9]+)/$', tile_detail, name='tile_detail'),
    url(r'^action/$', action_detail),
    url(r'^game_test/$', game_test),
    url(r'^games/$', GameList.as_view()),
    url(r'^games/(?P<pk>[0-9]+)/$', game_detail, name='game_detail'),
    url(r'^users/$', UserList.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', UserDetail.as_view()),
    url(r'^generate_map/$', generate_map),

]

urlpatterns = format_suffix_patterns(urlpatterns)

authentication/forms.py
from django import forms
from django.forms.widgets import PasswordInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=32)
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder': 'Password'}))


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    def clean(self, *args, **kwargs):
        email = self.cleaned_data['email']
        email_exists = User.objects.filter(email=email).exists()
        if email_exists:
            raise forms.ValidationError("This email is already associated with a user.")
        else:
            return self.cleaned_data

authentication/views.py
from django.shortcuts import render, redirect
from forms import LoginForm, RegistrationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as log_user_in
from django.contrib.auth.models import User
from map.models import GameMembership


def login(request):
    form = LoginForm()
    user = None
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                log_user_in(request, user)
                return redirect('dashboard:home')

    return render(request, "authentication/login.html", {
        'form': form,
        'user': user
    })


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1']
            )
            log_user_in(request, user)
            # Check for any GameMemberships they might have and convert to User references
            memberships = GameMembership.objects.filter(email=user.email)
            if memberships:
                for membership in memberships:
                    membership.user = user
                    membership.email = None
                    membership.save()
            return redirect('dashboard:home')

    return render(request, "authentication/register.html", {
        'form': form,
    })

authentication/templates/authentication/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>{% block title %}Login{% endblock %}</title>
    </head>
    <body>
    	

	{% block content %}

	{% endblock %}

	</body>
</html>

authentication/templates/authentication/login.html
{% extends "authentication/base.html" %}

{% block content %}
{% if user %}
{{ user }}
{% endif %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'authentication:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>


{% endblock %}

authentication/templates/authentication/register.html
{% block main_content %}

    <form method="post" class="form-horizontal">{% csrf_token %}
        <div class="row">
           <div class="col-sm-4 col-sm-offset-4">
                {% if message %}
                    <div class="alert alert-warning">
                        {{ message|safe }}
                    </div>
                {% endif %}
                {% if form.errors %}
                    <div class="alert alert-error clearfix">
                        <h4>Please correct the following:</h4>
                        <ul>
                            {% for field in form %}
                                {% if field.errors %}
                                    <li><a href="#{{ field.id_for_label }}" onclick="$('#{{ field.id_for_label }}').focus();return false;">{{ field.errors|join:", " }}</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                        {% if form.non_field_errors %}
                            {{ form.non_field_errors }}
                        {% endif %}
                    </div>
                {% endif %}

                {% for field in form %}
                    <div class="{{ field.name }} form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{field.id_for_label}}" class="control-label">
                            {{ field.label }}
                        </label>
                        {{ field }}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4 btns">
                <input type="submit" value="Save &amp; Continue" class="btn btn-primary btn-sma-md"/>
            </div>
        </div>
    </form>

{% endblock main_content %}