dashboard/urls.py
from django.conf.urls import url
from django.contrib import admin

from views import home, create_game, start_game_submit

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', home, name='home'),
    url(r'^create_game/', create_game, name='create_game'),
    url(r'^start_game_submit/$', start_game_submit, name='start_game_submit'),
]

django_canvas_hex/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from map import urls as map_urls
from authentication import urls as auth_urls
from dashboard import urls as dashboard_urls
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^map/', include(map_urls, namespace='map')),
    url(r'^authentication/', include(auth_urls, namespace='authentication')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
]

map/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from views import create_map, game, pre_game, GameList, GameDetail, \
    UserList, UserDetail, game_test, TileList, action_detail, \
    generate_map, tile_detail, game_detail

urlpatterns = [
    url(r'^create_map/', create_map, name='create_map'),
    url(r'^game/(?P<gid>\d+)', game, name='game'),
    url(r'^pre_game/(?P<gid>\d+)', pre_game, name='pre_game'),
    url(r'^tile_list/(?P<game_id>[0-9]+)/$', TileList.as_view()),
    url(r'^tile_detail/(?P<pk>[0-9]+)/$', tile_detail, name='tile_detail'),
    url(r'^action/$', action_detail),
    url(r'^game_test/$', game_test),
    url(r'^games/$', GameList.as_view()),
    url(r'^games/(?P<pk>[0-9]+)/$', game_detail, name='game_detail'),
    url(r'^users/$', UserList.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', UserDetail.as_view()),
    url(r'^generate_map/$', generate_map),

]

urlpatterns = format_suffix_patterns(urlpatterns)

dashboard/forms.py
from django import forms


class CreateGameForm(forms.Form):
    email1 = forms.EmailField()
    email2 = forms.EmailField(required=False)
    email3 = forms.EmailField(required=False)
    email4 = forms.EmailField(required=False)
    email5 = forms.EmailField(required=False)
    email6 = forms.EmailField(required=False)
    email7 = forms.EmailField(required=False)

dashboard/views.py
from __future__ import division

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from map.models import Game, GameMembership
from forms import CreateGameForm
from start_game import start_game




@login_required
def home(request):
    active_games = GameMembership.objects.filter(user=request.user)
    return render(request, "dashboard/home.html", {
        'user': request.user,
        'active_games': active_games
    })


@login_required
def create_game(request):
    form = CreateGameForm()
    return render(request, "dashboard/create_game.html", {
        'user': request.user,
        'form': form
    })


def start_game_submit(request):
    form = CreateGameForm()
    if request.method == 'POST':
        form = CreateGameForm(request.POST)
        if form.is_valid():
            start_game(request.user, form)

    return redirect('dashboard:home')

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
    	<meta charset="utf-8">
    	<title>{% block title %}Login{% endblock %}</title>
    </head>
    <body>
    	what

	{% block content %}

	{% endblock %}

	</body>
</html>

dashboard/templates/dashboard/create_game.html
{% extends "map/base.html" %}

{% block content %}
<p>Create Game Page</p>
{% if form.errors %}
{{ form.errors }}
{% endif %}

<form action="{% url 'dashboard:start_game_submit' %}" method="post">
{% csrf_token %}
{% for field in form %}
    {{ field.label }}{{ field }}
{% endfor %}

<input type="submit" value="Create Game" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock content %}

dashboard/templates/dashboard/home.html
{% block content %}
<p>Logged in!</p>
{{ user }}

<a href="{% url 'dashboard:create_game' %}">Create Game</a>
<h3>Active Games</h3>
    {% for membership in active_games %}
        {% if membership.game.status == 'invite_phase' %}
            <p>Game ID: <a href="{% url 'map:pre_game' gid=membership.game.id %}">{{ membership.game.id }}</a></p>
        {% elif membership.game.status == 'playing' %}
            <p>Game ID: <a href="{% url 'map:game' gid=membership.game.id %}">{{ membership.game.id }}</a></p>
        {% endif %}
    {% endfor %}
{% endblock content %}